#                              YB-Productions
# Title: Personalized Medical Recommendation System with Machine Learning Fundamentals




# Description:

Welcome to our Personalized Medical Recommendation System, a powerful platform designed to assist users in understanding and managing their health. Leveraging the capabilities of machine learning, our system analyzes user-input symptoms to predict potential diseases accurately.

# Import and Mount

In [129]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.2.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author:
Author-email:
License: new BSD
Location: C:\ProgramData\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: imbalanced-learn

# 1.  load dataset

In [435]:
import pandas as pd

In [436]:
base_path= "/content/drive/MyDrive/MedicineRecDB/datasets-new"
dataset = pd.read_csv(f"{base_path}/Training-Ex.csv")


# remove duplicate rows
dataset = dataset.drop_duplicates()
print("Dataset shape after removing duplicates:", dataset.shape)

Dataset shape after removing duplicates: (325, 133)

In [437]:
dataset

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6600,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Depression Disorder
6720,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Heat Stroke
6840,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Motion Sickness
6960,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Ear Infection
7080,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Allergic Rhinitis

### Count Uniq Diseases

In [438]:
unique_prognosis_count = dataset['prognosis'].nunique()
print(f"Number of unique prognoses in the dataset: {unique_prognosis_count}")

Number of unique prognoses in the dataset: 57

In [439]:
# vals = dataset.values.flatten()

In [440]:
dataset.shape  # gives total count of dataitems

(325, 133)

# 2. Train test split
- `train_test_split` function is commonly used in machine learning tasks to split a dataset into two separate sets: one for training a model and one  for testing the model's performance.
- `LabelEncoder` is used for encoding categorical (text-based) data into numerical data, which is often required by machine learning algorithms. Here prognosis is to be read..but computer reads only numbers..so represent it as number

In [441]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

### 1. Check Disease Validity
-  We need atleast 2 rows for 1 disease

In [442]:
counts = dataset['prognosis'].value_counts()
print(counts[counts < 2])

prognosis
Hypertension               1
Diabetes                   1
Acute Sinusitis            1
Gastritis                  1
Bronchitis                 1
Tonsillitis                1
Conjunctivitis             1
Food Poisoning             1
Kidney Infection           1
Urinary Tract Infection    1
Anxiety Disorder           1
Depression Disorder        1
Heat Stroke                1
Motion Sickness            1
Ear Infection              1
Allergic Rhinitis          1
Name: count, dtype: int64

### 2. Oversample single count rows

In [443]:
counts = dataset['prognosis'].value_counts()
single_classes = counts[counts == 1].index

extra_rows = dataset[dataset['prognosis'].isin(single_classes)]
dataset = pd.concat([dataset, extra_rows], ignore_index=True)

In [444]:
# Get training and Testing Data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

X = dataset.drop('prognosis', axis=1)
y = dataset['prognosis']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    stratify=y_encoded,
    random_state=42
)

### 3. Verify Data

In [445]:
# Get disease list
diseases_list = dict(enumerate(le.classes_))
diseases_list

{0: '(vertigo) Paroymsal  Positional Vertigo',
 1: 'AIDS',
 2: 'Acne',
 3: 'Acute Sinusitis',
 4: 'Alcoholic hepatitis',
 5: 'Allergic Rhinitis',
 6: 'Allergy',
 7: 'Anxiety Disorder',
 8: 'Arthritis',
 9: 'Bronchial Asthma',
 10: 'Bronchitis',
 11: 'Cervical spondylosis',
 12: 'Chicken pox',
 13: 'Chronic cholestasis',
 14: 'Common Cold',
 15: 'Conjunctivitis',
 16: 'Dengue',
 17: 'Depression Disorder',
 18: 'Diabetes',
 19: 'Diabetes ',
 20: 'Dimorphic hemmorhoids(piles)',
 21: 'Drug Reaction',
 22: 'Ear Infection',
 23: 'Food Poisoning',
 24: 'Fungal infection',
 25: 'GERD',
 26: 'Gastritis',
 27: 'Gastroenteritis',
 28: 'Heart attack',
 29: 'Heat Stroke',
 30: 'Hepatitis B',
 31: 'Hepatitis C',
 32: 'Hepatitis D',
 33: 'Hepatitis E',
 34: 'Hypertension',
 35: 'Hypertension ',
 36: 'Hyperthyroidism',
 37: 'Hypoglycemia',
 38: 'Hypothyroidism',
 39: 'Impetigo',
 40: 'Jaundice',
 41: 'Kidney Infection',
 42: 'Malaria',
 43: 'Migraine',
 44: 'Motion Sickness',
 45: 'Osteoarthristis',
 46: 'Paralysis (brain hemorrhage)',
 47: 'Peptic ulcer diseae',
 48: 'Pneumonia',
 49: 'Psoriasis',
 50: 'Tonsillitis',
 51: 'Tuberculosis',
 52: 'Typhoid',
 53: 'Urinary Tract Infection',
 54: 'Urinary tract infection',
 55: 'Varicose veins',
 56: 'hepatitis A'}

In [446]:
disease_array = []
for disease_id, disease_name in diseases_list.items():
    disease_array.append({"id": disease_id, "name": disease_name})

print(disease_array)

[{'id': 0, 'name': '(vertigo) Paroymsal  Positional Vertigo'}, {'id': 1, 'name': 'AIDS'}, {'id': 2, 'name': 'Acne'}, {'id': 3, 'name': 'Acute Sinusitis'}, {'id': 4, 'name': 'Alcoholic hepatitis'}, {'id': 5, 'name': 'Allergic Rhinitis'}, {'id': 6, 'name': 'Allergy'}, {'id': 7, 'name': 'Anxiety Disorder'}, {'id': 8, 'name': 'Arthritis'}, {'id': 9, 'name': 'Bronchial Asthma'}, {'id': 10, 'name': 'Bronchitis'}, {'id': 11, 'name': 'Cervical spondylosis'}, {'id': 12, 'name': 'Chicken pox'}, {'id': 13, 'name': 'Chronic cholestasis'}, {'id': 14, 'name': 'Common Cold'}, {'id': 15, 'name': 'Conjunctivitis'}, {'id': 16, 'name': 'Dengue'}, {'id': 17, 'name': 'Depression Disorder'}, {'id': 18, 'name': 'Diabetes'}, {'id': 19, 'name': 'Diabetes '}, {'id': 20, 'name': 'Dimorphic hemmorhoids(piles)'}, {'id': 21, 'name': 'Drug Reaction'}, {'id': 22, 'name': 'Ear Infection'}, {'id': 23, 'name': 'Food Poisoning'}, {'id': 24, 'name': 'Fungal infection'}, {'id': 25, 'name': 'GERD'}, {'id': 26, 'name': 'Gastritis'}, {'id': 27, 'name': 'Gastroenteritis'}, {'id': 28, 'name': 'Heart attack'}, {'id': 29, 'name': 'Heat Stroke'}, {'id': 30, 'name': 'Hepatitis B'}, {'id': 31, 'name': 'Hepatitis C'}, {'id': 32, 'name': 'Hepatitis D'}, {'id': 33, 'name': 'Hepatitis E'}, {'id': 34, 'name': 'Hypertension'}, {'id': 35, 'name': 'Hypertension '}, {'id': 36, 'name': 'Hyperthyroidism'}, {'id': 37, 'name': 'Hypoglycemia'}, {'id': 38, 'name': 'Hypothyroidism'}, {'id': 39, 'name': 'Impetigo'}, {'id': 40, 'name': 'Jaundice'}, {'id': 41, 'name': 'Kidney Infection'}, {'id': 42, 'name': 'Malaria'}, {'id': 43, 'name': 'Migraine'}, {'id': 44, 'name': 'Motion Sickness'}, {'id': 45, 'name': 'Osteoarthristis'}, {'id': 46, 'name': 'Paralysis (brain hemorrhage)'}, {'id': 47, 'name': 'Peptic ulcer diseae'}, {'id': 48, 'name': 'Pneumonia'}, {'id': 49, 'name': 'Psoriasis'}, {'id': 50, 'name': 'Tonsillitis'}, {'id': 51, 'name': 'Tuberculosis'}, {'id': 52, 'name': 'Typhoid'}, {'id': 53, 'name': 'Urinary Tract Infection'}, {'id': 54, 'name': 'Urinary tract infection'}, {'id': 55, 'name': 'Varicose veins'}, {'id': 56, 'name': 'hepatitis A'}]

In [447]:
print(list(diseases_list.values()))

['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne', 'Acute Sinusitis', 'Alcoholic hepatitis', 'Allergic Rhinitis', 'Allergy', 'Anxiety Disorder', 'Arthritis', 'Bronchial Asthma', 'Bronchitis', 'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis', 'Common Cold', 'Conjunctivitis', 'Dengue', 'Depression Disorder', 'Diabetes', 'Diabetes ', 'Dimorphic hemmorhoids(piles)', 'Drug Reaction', 'Ear Infection', 'Food Poisoning', 'Fungal infection', 'GERD', 'Gastritis', 'Gastroenteritis', 'Heart attack', 'Heat Stroke', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Hypertension', 'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia', 'Hypothyroidism', 'Impetigo', 'Jaundice', 'Kidney Infection', 'Malaria', 'Migraine', 'Motion Sickness', 'Osteoarthristis', 'Paralysis (brain hemorrhage)', 'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tonsillitis', 'Tuberculosis', 'Typhoid', 'Urinary Tract Infection', 'Urinary tract infection', 'Varicose veins', 'hepatitis A']

In [448]:

y  # appears big so transfor to array using labelencoder func ie Y

0         Fungal infection
1         Fungal infection
2         Fungal infection
3         Fungal infection
4         Fungal infection
              ...
336    Depression Disorder
337            Heat Stroke
338        Motion Sickness
339          Ear Infection
340      Allergic Rhinitis
Name: prognosis, Length: 341, dtype: object

In [449]:
# Y #transformed appears small
y_encoded

array([24, 24, 24, 24, 24,  6,  6,  6,  6,  6, 25, 25, 25, 25, 25, 25, 25,
       13, 13, 13, 13, 13, 13, 13, 13, 21, 21, 21, 21, 21, 21, 47, 47, 47,
       47, 47, 47, 47,  1,  1,  1,  1,  1, 19, 19, 19, 19, 19, 19, 19, 19,
       19, 27, 27, 27, 27, 27,  9,  9,  9,  9,  9,  9,  9, 34, 35, 35, 35,
       35, 35, 35, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 11, 11, 11, 11,
       11, 11, 46, 46, 46, 46, 46, 40, 40, 40, 40, 40, 40, 40, 40, 40, 42,
       42, 42, 42, 42, 42, 42, 42, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 52, 52, 52, 52, 52, 52, 52,
       52, 52, 56, 56, 56, 56, 56, 56, 56, 56, 56, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 32,
       32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33,  4,  4,  4,  4,  4,
        4,  4,  4, 51, 51, 51, 51, 51, 51, 51, 51, 51, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 48, 48, 48, 48, 48, 48, 48, 48, 48, 20, 20, 20, 20,
       20, 20, 28, 28, 28, 28, 28, 55, 55, 55, 55, 55, 55, 55, 55, 38, 38,
       38, 38, 38, 38, 38, 38, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 45, 45, 45, 45, 45, 45, 45,  8,  8,  8,
        8,  8,  8,  0,  0,  0,  0,  0,  0,  0,  2,  2,  2,  2,  2, 54, 54,
       54, 54, 54, 49, 49, 49, 49, 49, 49, 49, 39, 39, 39, 39, 39, 39, 18,
        3, 26, 10, 50, 15, 23, 16, 52, 48, 41, 53, 38, 36,  7, 17, 29, 44,
       22,  5, 34, 18,  3, 26, 10, 50, 15, 23, 41, 53,  7, 17, 29, 44, 22,
        5])

In [450]:
X

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,pus_filled_pimples,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
337,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
338,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
339,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
340,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 3. Training Classifiers (Supervised Learning)

In [451]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# we have created 5 models here  mainly
# Dictionary Stores the Models

models = {
    'SVC': SVC(kernel='rbf', C=1, gamma='scale'),

    'RandomForest': RandomForestClassifier(
        n_estimators=200,
        max_depth=15,
        min_samples_split=5,
        random_state=42
    ),

    'GradientBoosting': GradientBoostingClassifier(
        n_estimators=150,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    ),

    'KNeighbors': KNeighborsClassifier(
        n_neighbors=7,
        weights='distance'
    ),

    'MultinomialNB': MultinomialNB()
}

# Loop through the models, train, test, and print results
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Test the model
    predictions = model.predict(X_test)

    # Calculate accuracy
    accuracy = accuracy_score(y_test, predictions)
    print(f"{model_name} Accuracy: {accuracy}")

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, predictions)
    print(f"{model_name} Confusion Matrix:")
    print(np.array2string(cm, separator=', '))

    print("\n" + "="*40 + "\n")

# in output 0, 0, 0 represent no error
# if 1 or 2 occur in it there are some error..here no error so perfect

# svc, or Support Vector Classifier, is a supervised machine learning algorithm that is used for classification tasks.
# It is a specific implementation of the Support Vector Machine (SVM) algorithm that is designed to find the hyperplane that
# best separates data points into different classes.

# We choose Random Forest

SVC Accuracy: 0.9565217391304348
SVC Confusion Matrix:
[[2, 0, 0, ..., 0, 0, 0],
 [0, 1, 0, ..., 0, 0, 0],
 [0, 0, 1, ..., 0, 0, 0],
 ...,
 [0, 0, 0, ..., 1, 0, 0],
 [0, 0, 0, ..., 0, 2, 0],
 [0, 0, 0, ..., 0, 0, 2]]

========================================

RandomForest Accuracy: 0.9710144927536232
RandomForest Confusion Matrix:
[[2, 0, 0, ..., 0, 0, 0],
 [0, 1, 0, ..., 0, 0, 0],
 [0, 0, 1, ..., 0, 0, 0],
 ...,
 [0, 0, 0, ..., 1, 0, 0],
 [0, 0, 0, ..., 0, 2, 0],
 [0, 0, 0, ..., 0, 0, 2]]

========================================

GradientBoosting Accuracy: 0.7391304347826086
GradientBoosting Confusion Matrix:
[[1, 0, 0, ..., 0, 0, 0],
 [0, 0, 0, ..., 0, 0, 0],
 [0, 0, 1, ..., 0, 0, 0],
 ...,
 [0, 0, 0, ..., 0, 0, 0],
 [0, 0, 0, ..., 0, 1, 0],
 [0, 0, 0, ..., 0, 0, 2]]

========================================

KNeighbors Accuracy: 0.9710144927536232
KNeighbors Confusion Matrix:
[[2, 0, 0, ..., 0, 0, 0],
 [0, 1, 0, ..., 0, 0, 0],
 [0, 0, 1, ..., 0, 0, 0],
 ...,
 [0, 0, 0, ..., 1, 0, 0],
 [0, 0, 0, ..., 0, 2, 0],
 [0, 0, 0, ..., 0, 0, 2]]

========================================

MultinomialNB Accuracy: 0.9565217391304348
MultinomialNB Confusion Matrix:
[[2, 0, 0, ..., 0, 0, 0],
 [0, 1, 0, ..., 0, 0, 0],
 [0, 0, 1, ..., 0, 0, 0],
 ...,
 [0, 0, 0, ..., 1, 0, 0],
 [0, 0, 0, ..., 0, 2, 0],
 [0, 0, 0, ..., 0, 0, 2]]

========================================

In [452]:
# from sklearn.model_selection import cross_val_score

# for name, model in models.items():
#     scores = cross_val_score(model, X, y_encoded, cv=5)
#     print(f"{name} CV Accuracy: {scores.mean():.4f}")

In [453]:
# from sklearn.metrics import classification_report, precision_score, recall_score, f1_score

# print("\n===== Additional Model Statistics =====")

# for model_name, model in models.items():
#     predictions = model.predict(X_test)

#     # Calculate Precision, Recall, F1-score
#     precision = precision_score(y_test, predictions, average='weighted', zero_division=0)
#     recall = recall_score(y_test, predictions, average='weighted', zero_division=0)
#     f1 = f1_score(y_test, predictions, average='weighted', zero_division=0)

#     print(f"\n{model_name} Metrics:")
#     print(f"  Precision: {precision:.4f}")
#     print(f"  Recall: {recall:.4f}")
#     print(f"  F1-score: {f1:.4f}")

#     # Print Classification Report
#     print(f"\n{model_name} Classification Report:")
#     print(classification_report(y_test, predictions, target_names=le.classes_, zero_division=0))

#     print("="*60)

# Testing single prediction

In [454]:
# # selecting svc
# svc = SVC(kernel='linear')
# svc.fit(X_train,y_train)
# ypred = svc.predict(X_test)
# accuracy_score(y_test,ypred)

#using RFC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.927536231884058

In [415]:
# # save svc
# import pickle
# pickle.dump(svc,open('svc.pkl','wb'))

#write binary

# pickle sereializes or deserializes object in py using piclke module..serialize means convert to binary and
# deserialize ..viceversa

In [455]:
# save RFC
import pickle
# pickle.dump(model,open('model.pkl','wb'))
pickle.dump(model,open('model-Ex.pkl','wb'))

In [456]:
# load model
# model = pickle.load(open('model.pkl','rb'))
model = pickle.load(open('model-Ex.pkl','rb'))

In [457]:
# test 1:
print("predicted disease :",model.predict(X_test.iloc[0].values.reshape(1,-1)))
print("Actual Disease :", y_test[0])

predicted disease : [47]
Actual Disease : 47

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [458]:
# test 2:
print("predicted disease :",model.predict(X_test.iloc[10].values.reshape(1,-1)))
print("Actual Disease :", y_test[10])

predicted disease : [38]
Actual Disease : 38

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [459]:
pred = model.predict(X_test.iloc[0].values.reshape(1,-1))
print("Predicted disease:", le.inverse_transform(pred))
print("Actual disease:", le.inverse_transform([y_test[0]]))

Predicted disease: ['Peptic ulcer diseae']
Actual disease: ['Peptic ulcer diseae']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

# 4. Recommendation System and Prediction

## load database and use logic for recommendations

In [460]:
# sym_des = pd.read_csv(f"{base_path}/symtoms_df.csv")
# precautions = pd.read_csv(f"{base_path}/precautions_df.csv")
# workout = pd.read_csv(f"{base_path}/workout_df.csv")
# description = pd.read_csv(f"{base_path}/description.csv")
# medications = pd.read_csv(f"{base_path}/medications.csv")
# diets = pd.read_csv(f"{base_path}/diets.csv")

sym_des = pd.read_csv(f"{base_path}/symtoms_df-Ex.csv")
precautions = pd.read_csv(f"{base_path}/precautions_df-Ex.csv")
workout = pd.read_csv(f"{base_path}/workout_df-Ex.csv")
description = pd.read_csv(f"{base_path}/description-ex.csv")
medications = pd.read_csv(f"{base_path}/medications-Ex.csv")
diets = pd.read_csv(f"{base_path}/diets-Ex.csv")

In [461]:
medications

,Disease,Medication
0,Fungal infection,"['Antifungal Diet', 'Probiotics', 'Garlic', 'C..."
1,Allergy,"['Elimination Diet', 'Omega-3-rich foods', 'Vi..."
2,GERD,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
3,Chronic cholestasis,"['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot..."
4,Drug Reaction,"['Antihistamine Diet', 'Omega-3-rich foods', '..."
5,Peptic ulcer disease,"['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'..."
6,AIDS,"['Balanced Diet', 'Protein-rich foods', 'Fruit..."
7,Diabetes,"['Low-Glycemic Diet', 'Fiber-rich foods', 'Lea..."
8,Gastroenteritis,"['Bland Diet', 'Bananas', 'Rice', 'Applesauce'..."
9,Bronchial Asthma,"['Anti-Inflammatory Diet', 'Omega-3-rich foods..."
10,Hypertension,"['DASH Diet', 'Low-sodium foods', 'Fruits and ..."
11,Migraine,"['Migraine Diet', 'Low-Tyramine Diet', 'Caffei..."
12,Cervical spondylosis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
13,Paralysis (brain hemorrhage),"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
14,Jaundice,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
15,Malaria,"['Malaria Diet', 'Hydration', 'High-Calorie Di..."
16,Chicken pox,"['Chicken Pox Diet', 'High-Calorie Diet', 'Sof..."
17,Dengue,"['Dengue Diet', 'Hydration', 'High-Calorie Die..."
18,Typhoid,"['Typhoid Diet', 'High-Calorie Diet', 'Soft an..."
19,hepatitis A,"['Hepatitis A Diet', 'High-Calorie Diet', 'Sof..."
20,Hepatitis B,"['Hepatitis B Diet', 'High-Calorie Diet', 'Sof..."
21,Hepatitis C,"['Hepatitis C Diet', 'High-Calorie Diet', 'Sof..."
22,Hepatitis D,"['Hepatitis D Diet', 'High-Calorie Diet', 'Sof..."
23,Hepatitis E,"['Hepatitis E Diet', 'High-Calorie Diet', 'Sof..."
24,Alcoholic hepatitis,"['Liver-Healthy Diet', 'Low-fat Diet', 'Fruits..."
25,Tuberculosis,"['TB Diet', 'High-Calorie Diet', 'Soft and bla..."
26,Common Cold,"['Cold Diet', 'Hydration', 'Warm fluids', 'Res..."
27,Pneumonia,"['Pneumonia Diet', 'High-Calorie Diet', 'Soft ..."
28,Dimorphic hemmorhoids(piles),"['Hemorrhoids Diet', 'High-Fiber Diet', 'Hydra..."
29,Heart attack,"['Heart-Healthy Diet', 'Low-sodium foods', 'Fr..."
30,Varicose veins,"['Varicose Veins Diet', 'High-Fiber Diet', 'Fr..."
31,Hypothyroidism,"['Hypothyroidism Diet', 'Iodine-rich foods', '..."
32,Hyperthyroidism,"['Hyperthyroidism Diet', 'Low-Iodine Diet', 'C..."
33,Hypoglycemia,"['Hypoglycemia Diet', 'Complex carbohydrates',..."
34,Osteoarthristis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
35,Arthritis,"['Arthritis Diet', 'Anti-Inflammatory Diet', '..."
36,(vertigo) Paroymsal Positional Vertigo,"['Vertigo Diet', 'Low-Salt Diet', 'Hydration',..."
37,Acne,"['Acne Diet', 'Low-Glycemic Diet', 'Hydration'..."
38,Urinary tract infection,"['UTI Diet', 'Hydration', 'Cranberry juice', '..."
39,Psoriasis,"['Psoriasis Diet', 'Anti-Inflammatory Diet', '..."
40,Impetigo,"['Impetigo Diet', 'Antibiotic treatment', 'Fru..."
41,Acute Sinusitis,"['Warm fluids','Vitamin C foods','Ginger','Gar..."
42,Gastritis,"['Low-acid diet','Bananas','Oatmeal','Boiled v..."
43,Bronchitis,"['Warm soups','Honey','Ginger tea','Vitamin C ..."
44,Tonsillitis,"['Warm liquids','Soft foods','Honey','Herbal t..."
45,Conjunctivitis,"['Vitamin A foods','Carrots','Leafy greens','C..."
46,Food Poisoning,"['Oral rehydration fluids','Bananas','Rice','T..."
47,Dengue,"['Papaya leaf juice','Coconut water','Pomegran..."
48,Typhoid,"['Soft foods','Boiled vegetables','Bananas','R..."
49,Pneumonia,"['Protein rich diet','Warm soups','Garlic','Vi..."
50,Kidney Infection,"['Cranberry juice','Plenty of water','Fruits',..."
51,Urinary Tract Infection,"['Cranberry juice','Water','Probiotic yogurt',..."
52,Hypothyroidism,"['Iodine rich foods','Whole grains','Seafood',..."
53,Hyperthyroidism,"['Calcium rich foods','Broccoli','Cabbage','Wh..."
54,Anxiety Disorder,"['Magnesium rich foods','Dark chocolate','Leaf..."
55,Depression Disorder,"['Omega-3 foods','Fish','Whole grains','Fruits']"
56,Heat Stroke,"['Electrolyte drinks','Watermelon','Coconut wa..."
57,Motion Sickness,"['Ginger','Crackers','Peppermint tea','Bananas']"
58,Ear Infection,"['Vitamin C foods','Garlic','Warm soups','Frui..."
59,Allergic Rhinitis,"['Anti-inflammatory foods','Ginger','Turmeric'..."

In [462]:
#============================================================
# custome and helping functions
#==========================helper funtions================
def helper(dis):
    desc = description[description['Disease'] == predicted_disease]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']


    return desc,pre,med,die,wrkout

symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
# diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}





# Model Prediction function
# def get_predicted_value(patient_symptoms):
#     input_vector = np.zeros(len(symptoms_dict))
#     for item in patient_symptoms:
#         input_vector[symptoms_dict[item]] = 1
#     return diseases_list[model.predict([input_vector])[0]]

def get_predicted_value(symptoms):

    input_vector = np.zeros(len(X.columns))

    for symptom in symptoms:
        if symptom in X.columns:
            index = X.columns.get_loc(symptom)
            input_vector[index] = 1

    prediction = model.predict([input_vector])

    return le.inverse_transform(prediction)[0]

In [463]:
# Test 1
# Split the user's input into a list of symptoms (assuming they are comma-separated) # itching,skin_rash,nodal_skin_eruptions
symptoms = input("Enter your symptoms.......")
user_symptoms = [s.strip() for s in symptoms.split(',')]
# Remove any extra characters, if any
user_symptoms = [symptom.strip("[]' ") for symptom in user_symptoms]
predicted_disease = get_predicted_value(user_symptoms)

desc, pre, med, die, wrkout = helper(predicted_disease)

print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter your symptoms.......headache,blurred_and_distorted_vision,visual_disturbances,stiff_neck,excessive_hunger
=================predicted disease============
Migraine
=================description==================
Migraine is a type of headache that often involves severe pain and sensitivity to light and sound.
=================precautions==================
1 :  meditation
2 :  reduce stress
3 :  use poloroid glasses in sun
4 :  consult doctor
=================medications==================
5 :  ['Migraine Diet', 'Low-Tyramine Diet', 'Caffeine withdrawal', 'Hydration', 'Magnesium-rich foods']
=================workout==================
6 :  Identify and avoid trigger foods
7 :  Stay hydrated
8 :  Include magnesium-rich foods
9 :  Consume omega-3 fatty acids
10 :  Limit caffeine and alcohol
11 :  Consume riboflavin-rich foods
12 :  Limit processed foods
13 :  Maintain regular meal times
14 :  Consult a healthcare professional
15 :  Manage stress
=================diets==================
16 :  ['Migraine Diet', 'Low-Tyramine Diet', 'Caffeine withdrawal', 'Hydration', 'Magnesium-rich foods']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

# Multiple Testcases

In [464]:
# ===============================
# TEST SYMPTOM SETS
# ===============================

test_cases = [
"headache,blurred_and_distorted_vision,visual_disturbances,stiff_neck,excessive_hunger",
"continuous_sneezing,runny_nose,congestion,throat_irritation,sinus_pressure",
"headache,chest_pain,dizziness,loss_of_balance,lack_of_concentration",
"vomiting,diarrhoea,abdominal_pain,dehydration,nausea",
"high_fever,joint_pain,muscle_pain,headache,fatigue",
"acidity,indigestion,abdominal_pain,nausea,loss_of_appetite",
"cough,breathlessness,chest_pain,fatigue,phlegm",
"burning_micturition,spotting_ urination,abdominal_pain,fever,nausea",
"weight_gain,fatigue,depression,lethargy,dizziness",
"restlessness,sweating,fatigue,dizziness,headache",
"high_fever,headache,sweating,dizziness,fatigue",
"cough,high_fever,breathlessness,chest_pain,fatigue",
"redness_of_eyes,itching,skin_rash,headache,watering_from_eyes",
"continuous_sneezing,runny_nose,congestion,headache,fatigue"
]

# ===============================
# RUN TESTS
# ===============================

print("\n=========== MODEL TEST RESULTS ===========\n")

for i, case in enumerate(test_cases, 1):

    user_symptoms = [s.strip() for s in case.split(",")]

    predicted_disease = get_predicted_value(user_symptoms)

    print(f"Test {i}")
    print("Symptoms:", case)
    print("Prediction:", predicted_disease)
    print("--------------------------------------")

=========== MODEL TEST RESULTS ===========

Test 1
Symptoms: headache,blurred_and_distorted_vision,visual_disturbances,stiff_neck,excessive_hunger
Prediction: Migraine
--------------------------------------
Test 2
Symptoms: continuous_sneezing,runny_nose,congestion,throat_irritation,sinus_pressure
Prediction: Allergic Rhinitis
--------------------------------------
Test 3
Symptoms: headache,chest_pain,dizziness,loss_of_balance,lack_of_concentration
Prediction: Hypertension
--------------------------------------
Test 4
Symptoms: vomiting,diarrhoea,abdominal_pain,dehydration,nausea
Prediction: Food Poisoning
--------------------------------------
Test 5
Symptoms: high_fever,joint_pain,muscle_pain,headache,fatigue
Prediction: Dengue
--------------------------------------
Test 6
Symptoms: acidity,indigestion,abdominal_pain,nausea,loss_of_appetite
Prediction: Gastritis
--------------------------------------
Test 7
Symptoms: cough,breathlessness,chest_pain,fatigue,phlegm
Prediction: Bronchitis
--------------------------------------
Test 8
Symptoms: burning_micturition,spotting_ urination,abdominal_pain,fever,nausea
Prediction: Urinary Tract Infection
--------------------------------------
Test 9
Symptoms: weight_gain,fatigue,depression,lethargy,dizziness
Prediction: Hypothyroidism
--------------------------------------
Test 10
Symptoms: restlessness,sweating,fatigue,dizziness,headache
Prediction: Anxiety Disorder
--------------------------------------
Test 11
Symptoms: high_fever,headache,sweating,dizziness,fatigue
Prediction: Heat Stroke
--------------------------------------
Test 12
Symptoms: cough,high_fever,breathlessness,chest_pain,fatigue
Prediction: Bronchitis
--------------------------------------
Test 13
Symptoms: redness_of_eyes,itching,skin_rash,headache,watering_from_eyes
Prediction: Conjunctivitis
--------------------------------------
Test 14
Symptoms: continuous_sneezing,runny_nose,congestion,headache,fatigue
Prediction: Allergic Rhinitis
--------------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [465]:
# Test 1
# Split the user's input into a list of symptoms (assuming they are comma-separated) # yellow_crust_ooze,red_sore_around_nose,small_dents_in_nails,inflammatory_nails,blister
symptoms = input("Enter your symptoms.......")
user_symptoms = [s.strip() for s in symptoms.split(',')]
# Remove any extra characters, if any
user_symptoms = [symptom.strip("[]' ") for symptom in user_symptoms]
predicted_disease = get_predicted_value(user_symptoms)

desc, pre, med, die, wrkout = helper(predicted_disease)

print("=================predicted disease============")
print(predicted_disease)
print("=================description==================")
print(desc)
print("=================precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter your symptoms.......yellow_crust_ooze,red_sore_around_nose,small_dents_in_nails,inflammatory_nails,blister
=================predicted disease============
Impetigo
=================description==================
Impetigo is a highly contagious skin infection causing red sores that can break open.
=================precautions==================
1 :  soak affected area in warm water
2 :  use antibiotics
3 :  remove scabs with wet compressed cloth
4 :  consult doctor
=================medications==================
5 :  ['Impetigo Diet', 'Antibiotic treatment', 'Fruits and vegetables', 'Hydration', 'Protein-rich foods']
=================workout==================
6 :  Maintain good hygiene
7 :  Stay hydrated
8 :  Consume nutrient-rich foods
9 :  Limit sugary foods and beverages
10 :  Include foods rich in vitamin C
11 :  Consult a healthcare professional
12 :  Follow medical recommendations
13 :  Avoid scratching
14 :  Take prescribed antibiotics
15 :  Practice wound care
=================diets==================
16 :  ['Impetigo Diet', 'Antibiotic treatment', 'Fruits and vegetables', 'Hydration', 'Protein-rich foods']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [344]:
# TO   use pycharm flask app
# but install this version in pycharm
import sklearn
print(sklearn.__version__)

1.6.1

# Tasks

## 1. Auto suggest Symptoms

In [ ]:
import pandas as pd
dataset = pd.read_csv(f"{base_path}/Training.csv")
symptoms = dataset.columns[:-1]   # remove 'prognosis'

symptom_list = list(symptoms)

print(symptom_list[:10])

['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing', 'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity', 'ulcers_on_tongue']

In [ ]:
def suggest_symptoms(user_input):

    user_input = user_input.lower()

    suggestions = [
        symptom for symptom in symptom_list
        if user_input in symptom.lower()
    ]

    return suggestions[:10]  # limit results

In [ ]:
suggest_symptoms("hea")

['headache', 'fast_heart_rate', 'blackheads']